version: "1.0"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: money_bot
    restart: unless-stopped
    command: sh -c "python main.py"
    env_file:
      - .env
  db:
    image: postgres:15
    container_name: db_money_check
    env_file: .env
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro




volumes:
  postgres_data: