version: "1.0"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: money_bot
    restart: always
    command: sh -c "python main.py"
    env_file:
      - .env
    volumes:
      - "./database/money.db:/bot/database/money.db"
